apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
  namespace: blog-api
spec:
  selector:
    matchLabels:
      tier: backend
      role: common
  template:
    metadata:
      labels:
        tier: backend
        role: common
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: blog-api
          image: ghcr.io/narumir/blog-api:0.0.5
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          envFrom:
            - secretRef:
                name: blog-api
          ports:
            - containerPort: 4000
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 10
            timeoutSeconds: 1
            terminationGracePeriodSeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4000
          #   periodSeconds: 1
          #   successThreshold: 5
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 1
          #   failureThreshold: 7
