apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-api
  namespace: blog-api
  labels:
    name: blog-api
spec:
  ingressClassName: nginx
  rules:
    - host: api.narumir.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: blog-api
                port:
                  number: 80
  tls:
    - hosts:
        - api.narumir.io
      secretName: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
  namespace: blog-api
spec:
  secretName: letsencrypt
  dnsNames:
    - api.narumir.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
