apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
  namespace: blog-web
spec:
  selector:
    matchLabels:
      tier: frontend
      role: common
  template:
    metadata:
      labels:
        tier: frontend
        role: common
    spec:
      containers:
      - name: blog-web
        image: ghcr.io/narumir/blog-web:0.0.5
        env:
          - name: API_SERVER
            value: http://blog-api.blog-api
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
