apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-web
  namespace: blog-web
  labels:
    name: blog-web
spec:
  ingressClassName: nginx
  rules:
    - host: narumir.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: blog-web
                port:
                  number: 80
  tls:
    - hosts:
        - narumir.io
      secret: letsencrypt
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
  namespace: blog-web
spec:
  secretName: letsencrypt
  dnsNames:
    - narumir.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
